export const states = [
  {
    id: 1,
    name: 'Rajasthan',
    image: require('../../../assets/states/rajasthan.jpg'),
    imagebnw: require('../../../assets/states/rajasthanbnw.jpg'),
    isActive: false,
  },
  {
    id: 2,
    name: 'Uttar Pradesh',
    image: require('../../../assets/states/UP.jpg'),
    imagebnw: require('../../../assets/states/UPbnw.jpg'),
    isActive: false,
  },
  {
    id: 3,
    name: 'Maharashtra',
    image: require('../../../assets/states/maharashtra.jpg'),
    imagebnw: require('../../../assets/states/maharashtrabnw.jpg'),
    isActive: false,
  },
  {
    id: 4,
    name: 'Bihar',
    image: require('../../../assets/states/bihar.jpg'),
    imagebnw: require('../../../assets/states/biharbnw.jpg'),
    isActive: false,
  },
  {
    id: 5,
    name: 'Madhya Pradesh',
    image: require('../../../assets/states/MadhyaPradesh.jpg'),
    imagebnw: require('../../../assets/states/MadhyaPradeshbnw.jpg'),
    isActive: false,
  },
  {
    id: 6,
    name: 'New Delhi',
    image: require('../../../assets/states/delhi.jpg'),
    imagebnw: require('../../../assets/states/delhibnw.jpg'),
    isActive: false,
  },
  {
    id: 7,
    name: 'All India',
    image: require('../../../assets/states/india.jpg'),
    imagebnw: require('../../../assets/states/indiabnw.jpg'),
    isActive: false,
  },
  {
    id: 8,
    name: 'Punjab',
    image: require('../../../assets/states/Punjab.jpg'),
    imagebnw: require('../../../assets/states/Punjabbnw.jpg'),
    isActive: false,
  },
  {
    id: 9,
    name: 'Gujarat',
    image: require('../../../assets/states/gujarat.jpg'),
    imagebnw: require('../../../assets/states/gujaratbnw.jpg'),
    isActive: false,
  },
  {
    id: 10,
    name: 'Haryana',
    image: require('../../../assets/states/haryana.jpg'),
    imagebnw: require('../../../assets/states/haryanabnw.jpg'),
    isActive: false,
  },
  {
    id: 11,
    name: 'Himachal Pradesh',
    image: require('../../../assets/states/HimachalPradesh.jpg'),
    imagebnw: require('../../../assets/states/HimachalPradeshbnw.jpg'),
    isActive: false,
  },
  {
    id: 12,
    name: 'Uttarakhand',
    image: require('../../../assets/states/uttarakhand.jpg'),
    imagebnw: require('../../../assets/states/uttarakhandbnw.jpg'),
    isActive: false,
  },
  {
    id: 13,
    name: 'West Bengal',
    image: require('../../../assets/states/westbengal.jpg'),
    imagebnw: require('../../../assets/states/westbengalbnw.jpg'),
    isActive: false,
  },
  {
    id: 14,
    name: 'Chattisgarh',
    image: require('../../../assets/states/chattisgarh.jpg'),
    imagebnw: require('../../../assets/states/chattisgarhbnw.jpg'),
    isActive: false,
  },
  /*{
    id: 13,
    name: 'Goa',
    image: require('../../../assets/states/goa.jpg'),
    imagebnw: require('../../../assets/states/goabnw.jpg'),
isActive: false,
  },
  */
];
